### ISSUE TITLE
Um branch  por funcionalidade.

### ISSUE THREAD

**Issue by rdrgzma** [cassiane/projeto5semestre#1]
Senhores e senhora.
Não seria interessante fazermos uma branch para cada funcionalidade e só fazer o merge na master/origin quando a tal funcionalidade estivesse concluída? Assim evitamos os commits com funcionalidades incompletas ( como os que eu fiz) e só integraríamos as funcionalidades "funcionando". Os commits seriam periódicos, em cada branch,  para podermos acompanhar o andamento dos trabalhos mas só iriam para a master as funcionalidades completamente concluídas.
O que acham de aplicarmos isso na próxima sprint?

**Comment by olecramsl** [comment]
Parece-me uma boa ideia, mas vou ter q estudar um pouco esse negócio de branch hehehe. Também é importante quebrarmos as funcionalidades em pequenas partes (checklist do cartão do Trello) para que possamos fazer merges no origin dessas partes, já que a funcionalidade de um pode ser necessária para outro.

[]'s
Marcelo

Enviado de meu ASUS

-------- Mensagem Original --------
De:Márcio RdeR <notifications@github.com>
Enviado em:Mon, 05 Sep 2016 09:07:28 -0300
Para:cassiane/projeto5semestre <projeto5semestre@noreply.github.com>
Assunto:[cassiane/projeto5semestre] Um branch por funcionalidade. (#1)

**Comment by rdrgzma** [comment]
Ah... sim.. claro...Tem essa história de compartilhar as coisas... nessa primeira sprint as funcionalidades são mais independentes mas depois acho que com o tempo ficarão mais dependente uma das outras. Mas trabalhar com branch é tranquilo só tem que se ligar na hora do push que por padrão vai sempre para a origin.
